### ISSUE TITLE
Dont see device

### ISSUE THREAD

**Issue by Mimouss56** [sydspost/Domoticz-WiZ-connected-plugin#16]
Hi,
I need some help for found my devices
All my devices are with ip 192.168.1.* and find on DHCP
I need to know what subnet and port i need to write

![image](https://user-images.githubusercontent.com/61914395/147135032-6d600aff-bd21-46bb-b199-23ee012a5184.png)

**Comment by Mimouss56** [comment]
Right now i wrote 192.168.1.0/24 but nothing work

**Comment by sydspost** [comment]
The subnet config you made is ok. But the plugin does a recursieve DNS lookup to determ the hostname of the device. So please setup An DNS server, f.i. on yout router, OR add the devices with their FQDN and ip-address to the /etc/hosts file of your Domoticz server

**Comment by Mimouss56** [comment]
Can you explain how can i do in linux for setup DNS server or add the devices with their FQDN and ip-address to the /etc/hosts file ?
