### ISSUE TITLE
Pi freezes temporarely for 5 sec... every 10 secs.....

### ISSUE THREAD

**Issue by danieloSD** [sydspost/Domoticz-WiZ-connected-plugin#7]
I got the WIZ lights to work properly with this plugin.  Now that everything works the system seems to stop responding for like 5 seconds every 10 seconds or so... not just domoticz but it does the same if I ssh into the pi.  It's PI4. Raspbian buster and domoticz beta updates (wiz does not work with stable version)

**Comment by sydspost** [comment]
Guess this issue is solved and close it. If the issue is niet solved, please deel free to reopen it.
